import { db } from '../index.js'
import { brokers } from '../schema.js'
import { sql } from 'drizzle-orm'

export async function seedBrokers(database: any = db) {
  try {
    const existing = await database.select({ count: sql<number>`count(*)` }).from(brokers)
    const count = Number(existing[0]?.count || 0)

    if (count > 0) {
      console.log('Les brokers existent déjà. Seed des brokers ignoré.')
      return
    }

    console.log('Insertion des brokers...')
    await database.insert(brokers).values([
  {
    "name": "Accenture",
    "slug": "accenture",
    "emailContact": "Regulatory.Licenses@accenture.com",
    "website": "https://accenture.com",
    "optOutUrl": "https://yourdigitalrights.org/d/accenture.com",
    "category": "other",
    "region": "eu",
    "country": "IE",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "Accenture plc is an Irish multinational company that provides consulting and processing services.",
    "isVerified": true
  },
  {
    "name": "Accuity",
    "slug": "accuity",
    "emailContact": "consumer.documents@lexisnexis.com",
    "website": "https://accuity.com",
    "optOutUrl": "https://yourdigitalrights.org/d/accuity.com",
    "category": "risk-mitigation",
    "region": "eu",
    "country": "GB",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "Accuity – A LexisNexis® Risk Solutions Company",
    "isVerified": true
  },
  {
    "name": "adsquare GmbH",
    "slug": "adsquare-gmbh",
    "emailContact": "legal@adsquare.com",
    "website": "https://adsquare.com",
    "optOutUrl": "https://yourdigitalrights.org/d/adsquare.com",
    "category": "marketing",
    "region": "eu",
    "country": "DE",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "Adsquare is a location intelligence platform for marketers that helps brands connect people and places in a privacy-first world. They offer award-winning advertising solutions powered by location inte",
    "isVerified": true
  },
  {
    "name": "Altisource",
    "slug": "altisource",
    "emailContact": "Britt.Gottlieb@altisource.com",
    "website": "https://altisource.com",
    "optOutUrl": "https://yourdigitalrights.org/d/altisource.com",
    "category": "other",
    "region": "eu",
    "country": "LU",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "Servicer, Origination, Real Estate Investor, and Consumer Real Estate Solutions for mortgage and real estate professionals",
    "isVerified": true
  },
  {
    "name": "Audiencerate",
    "slug": "audiencerate",
    "emailContact": "privacy@audiencerate.com",
    "website": "https://audiencerate.com",
    "optOutUrl": "https://yourdigitalrights.org/d/audiencerate.com",
    "category": "other",
    "region": "eu",
    "country": "GB",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": null,
    "isVerified": true
  },
  {
    "name": "Azerion US Inc.",
    "slug": "azerion-us-inc",
    "emailContact": "dpo@azerion.com",
    "website": "https://azerion.com",
    "optOutUrl": null,
    "category": "marketing",
    "region": "eu",
    "country": "NL",
    "optOutMethod": "email",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "Azerion is a high-growth digital entertainment and media platform that connects advertisers, publishers, and game creators globally through technology solutions for digital advertising automation, rea",
    "isVerified": true
  },
  {
    "name": "Blis Global Ltd",
    "slug": "blis-global-ltd",
    "emailContact": "privacy@blis.com",
    "website": "https://blis.com",
    "optOutUrl": "https://yourdigitalrights.org/d/blis.com",
    "category": "marketing",
    "region": "eu",
    "country": "GB",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "Blis is an integrated planning and buying platform that delivers scaled, relevant, and high-performing audiences, helping the world’s largest brands and media agencies achieve their goals. Blis adhere",
    "isVerified": true
  },
  {
    "name": "BoardEx LLC",
    "slug": "boardex-llc",
    "emailContact": "privacy@altrata.com",
    "website": "https://boardex.com",
    "optOutUrl": "https://yourdigitalrights.org/d/boardex.com",
    "category": "marketing",
    "region": "eu",
    "country": "GB",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "BoardEx provides actionable people intelligence for organizations by mapping relationship paths to 1.7 million executives worldwide. As part of AltrataOfficial, BoardEx helps clients identify trusted ",
    "isVerified": true
  },
  {
    "name": "Brandwatch",
    "slug": "brandwatch",
    "emailContact": "privacy@brandwatch.com",
    "website": "https://brandwatch.com",
    "optOutUrl": "https://yourdigitalrights.org/d/brandwatch.com",
    "category": "other",
    "region": "eu",
    "country": "GB",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "Brandwatch is a digital consumer intelligence company headquartered in Brighton, England.",
    "isVerified": true
  },
  {
    "name": "Cognism",
    "slug": "cognism",
    "emailContact": "privacy@cognism.com",
    "website": "https://cognism.com",
    "optOutUrl": "https://yourdigitalrights.org/d/cognism.com",
    "category": "marketing",
    "region": "eu",
    "country": "GB",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "Cognism is GDPR-compliant B2B sales and marketing lead generation platform, providing B2B revenue teams with a blend of real-time company, people and event data to streamline prospecting, find and del",
    "isVerified": true
  },
  {
    "name": "Criteo",
    "slug": "criteo",
    "emailContact": "dpo@criteo.com",
    "website": "https://criteo.com",
    "optOutUrl": "https://yourdigitalrights.org/d/criteo.com",
    "category": "marketing",
    "region": "eu",
    "country": "FR",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "Criteo is an advertising company that provides online display advertisements.",
    "isVerified": true
  },
  {
    "name": "Databroker",
    "slug": "databroker",
    "emailContact": "info@data-broker.co.uk",
    "website": "https://data-broker.co.uk",
    "optOutUrl": "https://yourdigitalrights.org/d/data-broker.co.uk",
    "category": "marketing",
    "region": "eu",
    "country": "GB",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "Databroker is an impartial UK list broker providing quality B2B marketing lists including Mailing lists, Email & Telemarketing Data. Request a FREE sample.",
    "isVerified": true
  },
  {
    "name": "Emailmovers Ltd",
    "slug": "emailmovers-ltd",
    "emailContact": "compliance@emailmovers.com",
    "website": "https://emailmovers.com",
    "optOutUrl": "https://yourdigitalrights.org/d/emailmovers.com",
    "category": "marketing",
    "region": "eu",
    "country": "GB",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "Emailmovers is a leading global email marketing consultancy providing comprehensive email solutions for over 18 years, including data, design, and delivery services.",
    "isVerified": true
  },
  {
    "name": "eSite Analytics, Inc.",
    "slug": "esite-analytics-inc",
    "emailContact": "scott.love@kalibrate.com",
    "website": "https://kalibrate.com",
    "optOutUrl": null,
    "category": "other",
    "region": "eu",
    "country": "GB",
    "optOutMethod": "email",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "Kalibrate is a global company that provides data, consulting, and retail analytics platforms to businesses worldwide. With over 20 years of experience, Kalibrate has advised over 300 fuel and convenie",
    "isVerified": true
  },
  {
    "name": "Everyclick",
    "slug": "everyclick",
    "emailContact": "finance@everyclickltd.com",
    "website": "https://everyclick.com",
    "optOutUrl": "https://yourdigitalrights.org/d/everyclick.com",
    "category": "other",
    "region": "eu",
    "country": "GB",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "Make Everyclick your new search engine and you can help your favourite charity when you search the web.",
    "isVerified": true
  },
  {
    "name": "Evorra",
    "slug": "evorra",
    "emailContact": "warren.chang@evorra.com",
    "website": "https://evorra.com",
    "optOutUrl": "https://yourdigitalrights.org/d/evorra.com",
    "category": "marketing",
    "region": "eu",
    "country": "GB",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "Evorra is a SaaS marketplace for brands and agencies to simply build and scale the most valuable audiences in the world while respecting privacy and providing data source transparency.",
    "isVerified": true
  },
  {
    "name": "Excite Education",
    "slug": "excite-education",
    "emailContact": "support@help.mindspark.com",
    "website": "https://excite.com",
    "optOutUrl": "https://yourdigitalrights.org/d/excite.com",
    "category": "other",
    "region": "eu",
    "country": "GB",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "Your link to #onlineeducation education programs, news, study resources, #studentproblems and much more!",
    "isVerified": true
  },
  {
    "name": "Fifty",
    "slug": "fifty",
    "emailContact": "privacy@fifty.io",
    "website": "https://fifty.io",
    "optOutUrl": "https://yourdigitalrights.org/d/fifty.io",
    "category": "other",
    "region": "eu",
    "country": "GB",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": null,
    "isVerified": true
  },
  {
    "name": "Findmypast",
    "slug": "findmypast",
    "emailContact": "privacy@findmypast.co.uk",
    "website": "https://findmypast.co.uk",
    "optOutUrl": "https://yourdigitalrights.org/d/findmypast.co.uk",
    "category": "other",
    "region": "eu",
    "country": "GB",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "Findmypast is a UK-based online genealogy service owned, since 2007, by British company DC Thomson.",
    "isVerified": true
  },
  {
    "name": "Halfspace",
    "slug": "halfspace",
    "emailContact": "privacy@halfspace.co.uk",
    "website": "https://halfspace.co.uk",
    "optOutUrl": "https://yourdigitalrights.org/d/halfspace.co.uk",
    "category": "marketing",
    "region": "eu",
    "country": "GB",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "Halfspace Group is a company that specializes in data management, processing, and utilization. They believe that effective data management can unlock commercial growth for their clients. Their goal is",
    "isVerified": true
  },
  {
    "name": "Hybrid Theory",
    "slug": "hybrid-theory",
    "emailContact": "privacy@hybridtheory.com",
    "website": "https://hybridtheory.com",
    "optOutUrl": "https://yourdigitalrights.org/d/hybridtheory.com",
    "category": "marketing",
    "region": "eu",
    "country": "GB",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "We are Hybrid Theory, a new breed of digital services partner. We make the complex simple.",
    "isVerified": true
  },
  {
    "name": "ID5 Technology",
    "slug": "id5-technology",
    "emailContact": "privacy@id5.io",
    "website": "https://id5.io",
    "optOutUrl": "https://yourdigitalrights.org/d/id5.io",
    "category": "marketing",
    "region": "eu",
    "country": "GB",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "ID5 is a leading identity provider in digital advertising, offering addressability and data protection technologies to enhance engagement and compliance globally.",
    "isVerified": true
  },
  {
    "name": "IHS Markit",
    "slug": "ihs-markit",
    "emailContact": "privacy@spglobal.com",
    "website": "https://ihsmarkit.com",
    "optOutUrl": "https://yourdigitalrights.org/d/ihsmarkit.com",
    "category": "other",
    "region": "eu",
    "country": "GB",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "IHS Markit Ltd is an American-British information provider based in London.",
    "isVerified": true
  },
  {
    "name": "Informa Plc",
    "slug": "informa-plc",
    "emailContact": "GroupDPO@informa.com",
    "website": "https://informa.com",
    "optOutUrl": "https://yourdigitalrights.org/d/informa.com",
    "category": "other",
    "region": "eu",
    "country": "GB",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "Informa PLC is a British multinational publishing, business intelligence, and exhibitions group.",
    "isVerified": true
  },
  {
    "name": "Ipsos",
    "slug": "ipsos",
    "emailContact": "dpo.usa@ipsos.com",
    "website": "https://ipsos.com",
    "optOutUrl": "https://yourdigitalrights.org/d/ipsos.com",
    "category": "marketing",
    "region": "eu",
    "country": "FR",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "Ipsos is a global market research company specialized in advertising, loyalty, marketing, media, and public affairs market research. They provide accurate and relevant information to help clients make",
    "isVerified": true
  },
  {
    "name": "L.S. Mobile Apps Holding Ltd",
    "slug": "ls-mobile-apps-holding-ltd",
    "emailContact": "guy.hamawi@lsmapps.com",
    "website": "https://lsmapps.com",
    "optOutUrl": "https://yourdigitalrights.org/d/lsmapps.com",
    "category": "other",
    "region": "eu",
    "country": "GB",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "LSM Apps is a company that provides a contacts management app called Easy Contacts. This app allows users to easily manage their contacts by providing features such as backup, cleanup, and caller ID. ",
    "isVerified": true
  },
  {
    "name": "Locate Family",
    "slug": "locate-family",
    "emailContact": "no-email@optout.local",
    "website": "https://locatefamily.com",
    "optOutUrl": "https://yourdigitalrights.org/d/locatefamily.com",
    "category": "other",
    "region": "eu",
    "country": "HU",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "LocateFamily.com is a leading online platform that provides a range of services to help individuals locate and connect with their family members. Our user-friendly website allows users to search for a",
    "isVerified": true
  },
  {
    "name": "loopme.com",
    "slug": "loopmecom",
    "emailContact": "legal@loopme.com",
    "website": "https://loopme.com",
    "optOutUrl": "https://yourdigitalrights.org/d/loopme.com",
    "category": "marketing",
    "region": "eu",
    "country": "GB",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "LoopMe is a technology company that uses artificial intelligence (AI) to improve brand advertising performance and outcomes. LoopMe's core business helps brands and agencies achieve better advertising",
    "isVerified": true
  },
  {
    "name": "Matchbook Data LLC",
    "slug": "matchbook-data-llc",
    "emailContact": "mkercher@digitalenvoy.net",
    "website": "https://matchbookdata.com",
    "optOutUrl": "https://yourdigitalrights.org/d/matchbookdata.com",
    "category": "marketing",
    "region": "eu",
    "country": "GB",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "Matchbook is an identity resolution solution that helps clients connect the dots between customers and prospects in a fragmented data and marketing landscape. It allows clients to find the right audie",
    "isVerified": true
  },
  {
    "name": "Mimecast",
    "slug": "mimecast",
    "emailContact": "info@mimecast.com",
    "website": "https://mimecast.com",
    "optOutUrl": "https://yourdigitalrights.org/d/mimecast.com",
    "category": "other",
    "region": "eu",
    "country": "GB",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "Mimecast provides cutting-edge email protection, archiving, and continuity services for over 42,000 organizations globally, ensuring secure business communications and data management.",
    "isVerified": true
  },
  {
    "name": "Monevo Inc.",
    "slug": "monevo-inc",
    "emailContact": "usacompliance@monevo.com",
    "website": "https://monevo.com",
    "optOutUrl": "https://yourdigitalrights.org/d/monevo.com",
    "category": "risk-mitigation",
    "region": "eu",
    "country": "GB",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "Monevo is a leading B2B personal credit platform and API that connects consumers with lenders globally, aiming to be the central infrastructure for personal credit distribution worldwide.",
    "isVerified": true
  },
  {
    "name": "OnAudience Ltd",
    "slug": "onaudience-ltd",
    "emailContact": "privacy@onaudience.com",
    "website": "https://onaudience.com",
    "optOutUrl": "https://yourdigitalrights.org/d/onaudience.com",
    "category": "other",
    "region": "eu",
    "country": "GB",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "OnAudience is a global data provider that fuels digital campaigns and business solutions through high-quality data with global reach. They offer privacy-safe and GDPR-compliant data in over 200 market",
    "isVerified": true
  },
  {
    "name": "Outlogic",
    "slug": "outlogic",
    "emailContact": "privacy@outlogic.io",
    "website": "https://outlogic.io",
    "optOutUrl": "https://yourdigitalrights.org/d/outlogic.io",
    "category": "other",
    "region": "eu",
    "country": "GB",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "Outlogic is a provider of location data for the retail, real estate, and financial markets. Outlogic has exemplified high standards and best practices for the collection and use of location data while",
    "isVerified": true
  },
  {
    "name": "Pathway Ventures LLC",
    "slug": "pathway-ventures-llc",
    "emailContact": "privacyofficer@indivizio.com",
    "website": "https://indivizio.com",
    "optOutUrl": null,
    "category": "marketing",
    "region": "eu",
    "country": "HU",
    "optOutMethod": "email",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": null,
    "isVerified": true
  },
  {
    "name": "Permutive",
    "slug": "permutive",
    "emailContact": "privacy@permutive.com",
    "website": "https://permutive.com",
    "optOutUrl": "https://yourdigitalrights.org/d/permutive.com",
    "category": "marketing",
    "region": "eu",
    "country": "GB",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "The only publisher data platform built on edge computing. Get a demo today to find out how to grow data-driven ad revenue and succesfully diversify revenue.",
    "isVerified": true
  },
  {
    "name": "PwC",
    "slug": "pwc",
    "emailContact": "US_Privacy_Office@pwc.com",
    "website": "https://pwc.com",
    "optOutUrl": "https://yourdigitalrights.org/d/pwc.com",
    "category": "other",
    "region": "eu",
    "country": "ES",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "PwC is a global network of firms delivering world-class assurance, tax, and consulting services for your business.",
    "isVerified": true
  },
  {
    "name": "Quotient",
    "slug": "quotient",
    "emailContact": "privacy@quotient.com",
    "website": "https://quotient.com",
    "optOutUrl": "https://yourdigitalrights.org/d/quotient.com",
    "category": "marketing",
    "region": "eu",
    "country": "GB",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "Quotient's brand marketing tools help you target, optimize, and measure campaigns to drive engagement, valuable outcomes and maximize ROI. Learn more.",
    "isVerified": true
  },
  {
    "name": "RE-HOLD",
    "slug": "re-hold",
    "emailContact": "no-email@optout.local",
    "website": "https://rehold.com",
    "optOutUrl": "https://yourdigitalrights.org/d/rehold.com",
    "category": "other",
    "region": "eu",
    "country": "BE",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "Address and Property Directory | Rehold Complete US Address Directory. Search Address. Input your search on the residential or business property in the required field. Search can include house number,",
    "isVerified": true
  },
  {
    "name": "Rhetorik",
    "slug": "rhetorik",
    "emailContact": "research@rhetorik.com",
    "website": "https://rhetorik.com",
    "optOutUrl": "https://yourdigitalrights.org/d/rhetorik.com",
    "category": "other",
    "region": "eu",
    "country": "GB",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "The leading database of UK, EMEA and AsiaPac enterprise technology buyers. The leading data cleaning tools. Accelerate sales, drive growth.",
    "isVerified": true
  },
  {
    "name": "SciLeads",
    "slug": "scileads",
    "emailContact": "privacy@scileads.com",
    "website": "https://scileads.com",
    "optOutUrl": "https://yourdigitalrights.org/d/scileads.com",
    "category": "other",
    "region": "eu",
    "country": "GB",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": null,
    "isVerified": true
  },
  {
    "name": "SearchQuarry.com",
    "slug": "searchquarrycom",
    "emailContact": "no-email@optout.local",
    "website": "https://searchquarry.com",
    "optOutUrl": "https://yourdigitalrights.org/d/searchquarry.com",
    "category": "other",
    "region": "eu",
    "country": "BG",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "Search by name, phone number, license plate number, or VIN. View background records, civil records, liens, contact info, & more.",
    "isVerified": true
  },
  {
    "name": "Semasio",
    "slug": "semasio",
    "emailContact": "privacy@semasio.com",
    "website": "https://semasio.com",
    "optOutUrl": "https://yourdigitalrights.org/d/semasio.com",
    "category": "other",
    "region": "eu",
    "country": "DE",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "The days of “black box” targeting platforms are ending – gain complete control, transparency and ownership of your custom audience creation with Semasio.",
    "isVerified": true
  },
  {
    "name": "Sirdata",
    "slug": "sirdata",
    "emailContact": "dpo@sirdata.com",
    "website": "https://sirdata.com",
    "optOutUrl": "https://yourdigitalrights.org/d/sirdata.com",
    "category": "marketing",
    "region": "eu",
    "country": "FR",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "Sirdata offers a suite of multi-lever data solutions combining operational, technological and consulting expertise",
    "isVerified": true
  },
  {
    "name": "VEROMI",
    "slug": "veromi",
    "emailContact": "no-email@optout.local",
    "website": "https://veromi.com",
    "optOutUrl": null,
    "category": "other",
    "region": "eu",
    "country": "BE",
    "optOutMethod": "email",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "VEROMI is a technology company that specializes in providing identity verification solutions. Our advanced platform utilizes cutting-edge technology to verify the identity of individuals in real-time.",
    "isVerified": true
  },
  {
    "name": "yasni",
    "slug": "yasni",
    "emailContact": "info@yasni.com",
    "website": "https://yasni.com",
    "optOutUrl": "https://yourdigitalrights.org/d/yasni.com",
    "category": "people-search",
    "region": "eu",
    "country": "DE",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "Search phone, email, address for any name. News, pictures & links for any person. Find anyone on the internet with the world's largest free people search.",
    "isVerified": true
  },
  {
    "name": "Zeotap",
    "slug": "zeotap",
    "emailContact": "privacy@zeotap.com",
    "website": "https://zeotap.com",
    "optOutUrl": "https://yourdigitalrights.org/d/zeotap.com",
    "category": "marketing",
    "region": "eu",
    "country": "DE",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "gdpr_art17",
    "notes": "We are an award-winning agile technology company that empowers the safe use of telecom data globally across different industries starting with mobile advertising. As a team, we are driven entrepreneur",
    "isVerified": true
  },
  {
    "name": "Acxiom",
    "slug": "acxiom",
    "emailContact": "privacy@acxiom.com",
    "website": "https://acxiom.com",
    "optOutUrl": "https://yourdigitalrights.org/d/acxiom.com",
    "category": "marketing",
    "region": "us",
    "country": "US",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": "Acxiom is a Conway, Arkansas-based database marketing company.",
    "isVerified": true
  },
  {
    "name": "BeenVerified.com",
    "slug": "beenverifiedcom",
    "emailContact": "privacy@beenverified.com",
    "website": "https://beenverified.com",
    "optOutUrl": "https://yourdigitalrights.org/d/beenverified.com",
    "category": "people-search",
    "region": "us",
    "country": "US",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": "Search public records & VIN numbers online. Uncover names, phone numbers, addresses & emails. Check vehicle history for all car make & models. Start your search today!",
    "isVerified": true
  },
  {
    "name": "Clearbit",
    "slug": "clearbit",
    "emailContact": "privacy@clearbit.com",
    "website": "https://clearbit.com",
    "optOutUrl": "https://yourdigitalrights.org/d/clearbit.com",
    "category": "marketing",
    "region": "us",
    "country": "US",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": "The marketing data engine to deeply understand your customers, identify future prospects, & personalize every single marketing & sales interaction.",
    "isVerified": true
  },
  {
    "name": "Epsilon",
    "slug": "epsilon",
    "emailContact": "privacy@conversantmedia.com",
    "website": "https://conversantmedia.com",
    "optOutUrl": "https://yourdigitalrights.org/d/conversantmedia.com",
    "category": "marketing",
    "region": "us",
    "country": "US",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": "Epsilon® is an all-encompassing global marketing innovator. We provide unrivaled data intelligence and customer insights, world-class technology including loyalty, email and CRM platforms and data-dri",
    "isVerified": true
  },
  {
    "name": "Equifax",
    "slug": "equifax",
    "emailContact": "vtinquiries@equifax.com",
    "website": "https://equifax.com",
    "optOutUrl": "https://yourdigitalrights.org/d/equifax.com",
    "category": "other",
    "region": "us",
    "country": "US",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": "Get your credit report and Equifax credit score plus identity protection tools with daily monitoring and alerts today!",
    "isVerified": true
  },
  {
    "name": "Experian",
    "slug": "experian",
    "emailContact": "nerissa.rush@experian.com",
    "website": "https://experian.com",
    "optOutUrl": "https://yourdigitalrights.org/d/experian.com",
    "category": "other",
    "region": "us",
    "country": "US",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": "Experian is committed to helping you protect, understand, and improve your credit. Start with your free Experian credit report and FICO® score.",
    "isVerified": true
  },
  {
    "name": "Experian's Clarity Services",
    "slug": "experians-clarity-services",
    "emailContact": "SalesDepartment@clarityservices.com",
    "website": "https://clarityservices.com",
    "optOutUrl": "https://yourdigitalrights.org/d/clarityservices.com",
    "category": "risk-mitigation",
    "region": "us",
    "country": "US",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": "Experian's Clarity Services is a credit bureau that provides reporting on near-prime, non-prime and subprime consumers.",
    "isVerified": true
  },
  {
    "name": "FullContact",
    "slug": "fullcontact",
    "emailContact": "privacy@fullcontact.com",
    "website": "https://fullcontact.com",
    "optOutUrl": "https://yourdigitalrights.org/d/fullcontact.com",
    "category": "marketing",
    "region": "us",
    "country": "US",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": "FullContact Inc. is a privately held technology company that provides a suite of cloud-based software products for businesses, developers, and brands.",
    "isVerified": true
  },
  {
    "name": "Instant Checkmate",
    "slug": "instant-checkmate",
    "emailContact": "support@instantcheckmate.com",
    "website": "https://instantcheckmate.com",
    "optOutUrl": "https://yourdigitalrights.org/d/instantcheckmate.com",
    "category": "people-search",
    "region": "us",
    "country": "US",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": "Instant Checkmate is an online service that provides people finder, public record and criminal record information to individuals on a subscription basis. Instant Checkmate aggregates data from federal",
    "isVerified": true
  },
  {
    "name": "instantpeoplefinder.com",
    "slug": "instantpeoplefindercom",
    "emailContact": "no-email@optout.local",
    "website": "https://instantpeoplefinder.com",
    "optOutUrl": "https://yourdigitalrights.org/d/instantpeoplefinder.com",
    "category": "other",
    "region": "us",
    "country": null,
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": null,
    "isVerified": true
  },
  {
    "name": "Intelius",
    "slug": "intelius",
    "emailContact": "privacy@peopleconnect.us",
    "website": "https://intelius.com",
    "optOutUrl": "https://yourdigitalrights.org/d/intelius.com",
    "category": "people-search",
    "region": "us",
    "country": "US",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": "Intelius, Inc. is a public records business headquartered in Seattle, Washington, United States.",
    "isVerified": true
  },
  {
    "name": "LexisNexis",
    "slug": "lexisnexis",
    "emailContact": "legalnotices@lexisnexis.com",
    "website": "https://idanalytics.com",
    "optOutUrl": "https://yourdigitalrights.org/d/idanalytics.com",
    "category": "other",
    "region": "us",
    "country": "US",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": "LexisNexis is a leading global provider of legal, regulatory & business info & analytics. Get 24/7 help at https://t.co/CMPkdNEm6A or 800-543-6862",
    "isVerified": true
  },
  {
    "name": "Lusha",
    "slug": "lusha",
    "emailContact": "Privacy@Lusha.co",
    "website": "https://lusha.co",
    "optOutUrl": "https://yourdigitalrights.org/d/lusha.co",
    "category": "other",
    "region": "us",
    "country": "IL",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": "Lusha provides high quality, unique premium data where you need it most: On social networks & the web, in Salesforce or directly to your product.",
    "isVerified": true
  },
  {
    "name": "Lusha Systems Inc.",
    "slug": "lusha-systems-inc",
    "emailContact": "privacy@lusha.com",
    "website": "https://lusha.com",
    "optOutUrl": "https://yourdigitalrights.org/d/lusha.com",
    "category": "marketing",
    "region": "us",
    "country": "US",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": "Lusha provides high quality, unique premium data where you need it most: On social networks, the web, Salesforce or directly on your product. B2B engagement is based on trust. Lusha helps you build th",
    "isVerified": true
  },
  {
    "name": "MyLife.com",
    "slug": "mylifecom",
    "emailContact": "privacy@mylife.com",
    "website": "https://mylife.com",
    "optOutUrl": "https://yourdigitalrights.org/d/mylife.com",
    "category": "other",
    "region": "us",
    "country": "US",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": "Background Report, Get contact info & detailed background reports on anyone today at MyLife; Search others now or check & edit your own background report",
    "isVerified": true
  },
  {
    "name": "Nielsen",
    "slug": "nielsen",
    "emailContact": "corporatepressinquiries@nielsen.com",
    "website": "https://nielsen.com",
    "optOutUrl": "https://yourdigitalrights.org/d/nielsen.com",
    "category": "other",
    "region": "us",
    "country": "US",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": "Nielsen Holdings PLC is an American, UK-domiciled, information, data and market measurement firm.",
    "isVerified": true
  },
  {
    "name": "peoplefinder.com",
    "slug": "peoplefindercom",
    "emailContact": "no-email@optout.local",
    "website": "https://peoplefinder.com",
    "optOutUrl": null,
    "category": "people-search",
    "region": "us",
    "country": "US",
    "optOutMethod": "email",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": "Find people instantly. Search for someone by  their name, phone number or address. Inteilus provides phone numbers, previous addresses and background checks.",
    "isVerified": true
  },
  {
    "name": "peoplefinderonline.net",
    "slug": "peoplefinderonlinenet",
    "emailContact": "support@infotracer.com",
    "website": "https://peoplefinderonline.net",
    "optOutUrl": "https://yourdigitalrights.org/d/peoplefinderonline.net",
    "category": "other",
    "region": "us",
    "country": null,
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": null,
    "isVerified": true
  },
  {
    "name": "PeopleFinders",
    "slug": "peoplefinders",
    "emailContact": "affiliates@peoplefinders.com",
    "website": "https://people-finders.ws",
    "optOutUrl": "https://yourdigitalrights.org/d/people-finders.ws",
    "category": "people-search",
    "region": "us",
    "country": "US",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": "484889 peoplefinders.com is a public records business located in Sacramento, California.",
    "isVerified": true
  },
  {
    "name": "peoplefindersdaas.com",
    "slug": "peoplefindersdaascom",
    "emailContact": "privacy@peoplefindersdaas.com",
    "website": "https://peoplefindersdaas.com",
    "optOutUrl": "https://yourdigitalrights.org/d/peoplefindersdaas.com",
    "category": "other",
    "region": "us",
    "country": "US",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": null,
    "isVerified": true
  },
  {
    "name": "PeopleLooker",
    "slug": "peoplelooker",
    "emailContact": "privacy@peoplelooker.com",
    "website": "https://peoplelooker.com",
    "optOutUrl": "https://yourdigitalrights.org/d/peoplelooker.com",
    "category": "people-search",
    "region": "us",
    "country": "US",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": "Find social media accounts with ease. Lookup Twitter & LinkedIn profiles. Run a background check to uncover public records, email addresses, phone numbers and much more.",
    "isVerified": true
  },
  {
    "name": "PeopleSmart",
    "slug": "peoplesmart",
    "emailContact": "support@emailfinder.com",
    "website": "https://emailfinder.com",
    "optOutUrl": "https://yourdigitalrights.org/d/emailfinder.com",
    "category": "other",
    "region": "us",
    "country": "BR",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": "PeopleSmart helps you find business contact info for millions of professionals. Search for prospects by          company, job title, industry, or social profile.",
    "isVerified": true
  },
  {
    "name": "Pipl",
    "slug": "pipl",
    "emailContact": "mail@pipl.com",
    "website": "https://pipl.com",
    "optOutUrl": "https://yourdigitalrights.org/d/pipl.com",
    "category": "other",
    "region": "us",
    "country": "US",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": "Pipl is a people data company that makes it easy for anyone to get contact, social, demographic and professional information about people.    At Pipl’s core is its proprietary identity resolution engi",
    "isVerified": true
  },
  {
    "name": "Radaris",
    "slug": "radaris",
    "emailContact": "affiliate@radaris.com",
    "website": "https://radaris.com",
    "optOutUrl": "https://yourdigitalrights.org/d/radaris.com",
    "category": "people-search",
    "region": "us",
    "country": "US",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": "Radaris is a public records search engine. With Radaris you can find anyone in the United States and get their contact information or learn about their professional history. At Radaris each person has",
    "isVerified": true
  },
  {
    "name": "RocketReach",
    "slug": "rocketreach",
    "emailContact": "ca-privacy@rocketreach.co",
    "website": "https://rocketreach.co",
    "optOutUrl": "https://yourdigitalrights.org/d/rocketreach.co",
    "category": "other",
    "region": "us",
    "country": "US",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": "RocketReach is the most accurate and intuitive contact discovery tool, trusted by FORTUNE 500 companies including Google, Apple, Bank of America, Morgan Stanley, just to name a few.    RocketReach all",
    "isVerified": true
  },
  {
    "name": "Spokeo",
    "slug": "spokeo",
    "emailContact": "no-email@optout.local",
    "website": "https://bizshark.com",
    "optOutUrl": null,
    "category": "people-search",
    "region": "us",
    "country": "US",
    "optOutMethod": "email",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": "People search engine and free white pages finds phone, address, email, and photos. Find people by name, email, address, and phone for free.",
    "isVerified": true
  },
  {
    "name": "TransUnion",
    "slug": "transunion",
    "emailContact": "Sustainabit@transunion.com",
    "website": "https://transunion.com",
    "optOutUrl": "https://yourdigitalrights.org/d/transunion.com",
    "category": "other",
    "region": "us",
    "country": "US",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": "TransUnion is an American consumer credit reporting agency.",
    "isVerified": true
  },
  {
    "name": "TruthFinder",
    "slug": "truthfinder",
    "emailContact": "help@truthfinder.com",
    "website": "https://truthfinder.com",
    "optOutUrl": "https://yourdigitalrights.org/d/truthfinder.com",
    "category": "people-search",
    "region": "us",
    "country": "US",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": "TruthFinder is one of America’s most trusted background checking services. We provide an easy way to look up criminal records online.  Try a search today!",
    "isVerified": true
  },
  {
    "name": "Whitepages",
    "slug": "whitepages",
    "emailContact": "email@example.com",
    "website": "https://whitepages.com",
    "optOutUrl": "https://yourdigitalrights.org/d/whitepages.com",
    "category": "people-search",
    "region": "us",
    "country": "US",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": "Free White Pages to find people by name, phone number, email address, street address and much more.",
    "isVerified": true
  },
  {
    "name": "whitepages.plus",
    "slug": "whitepagesplus",
    "emailContact": "mail@whitepages.plus",
    "website": "https://whitepages.plus",
    "optOutUrl": "https://yourdigitalrights.org/d/whitepages.plus",
    "category": "other",
    "region": "us",
    "country": null,
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": null,
    "isVerified": true
  },
  {
    "name": "ZoomInfo",
    "slug": "zoominfo",
    "emailContact": "privacy@zoominfo.com",
    "website": "https://zoominfo.com",
    "optOutUrl": "https://yourdigitalrights.org/d/zoominfo.com",
    "category": "marketing",
    "region": "us",
    "country": "US",
    "optOutMethod": "form",
    "difficulty": "medium",
    "legalBasis": "ccpa",
    "notes": "ZoomInfo Technologies Inc. is an American subscription-based software as a service company based in Vancouver, Washington that sells access to its database of information about business people and com",
    "isVerified": true
  }
])

    console.log('77 brokers insérés avec succès')
  } catch (error) {
    console.error('Erreur lors de l\'exécution du seed des brokers:', error)
  }
}

if (process.argv[1]?.endsWith('brokers_seed.ts') || process.argv[1]?.endsWith('brokers_seed.js')) {
  seedBrokers()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error(err)
      process.exit(1)
    })
}
